import type { AnalysisCapability } from "./types.js";

export const ARENA_ANALYSIS_CAPABILITIES: readonly AnalysisCapability[] = [
  {
    id: "arena-concurrency-capacity",
    executionPhase: "discovery-core",
    knowledgeDomains: ["arena-lifecycle", "multiplayer-interleaving"],
    evidenceLevel: "semantic",
    cost: "cheap",
    tags: ["arena", "capacity", "multiplayer"],
    deterministic: true,
    contexts: [
      "REMOTE_GITHUB",
      "LOCAL_ARTIFACT",
      "LOCAL_MINECRAFT",
      "LIVE_MINECRAFT",
    ],
    producesTraits: ["structural-proof", "semantic-model"],
  },
  {
    id: "release-identity-consistency",
    executionPhase: "discovery-core",
    evidenceLevel: "static",
    cost: "cheap",
    tags: ["manifest", "release", "version"],
    deterministic: true,
    contexts: ["REMOTE_GITHUB", "LOCAL_ARTIFACT"],
    producesTraits: ["structural-proof"],
  },
  {
    id: "safe-config-resolution",
    executionPhase: "discovery-core",
    evidenceLevel: "semantic",
    cost: "moderate",
    tags: ["arena", "configuration", "coordinates", "script"],
    deterministic: true,
    contexts: [
      "REMOTE_GITHUB",
      "LOCAL_ARTIFACT",
    ],
    producesTraits: ["semantic-model"],
  },
  {
    id: "arena-replica-fidelity",
    executionPhase: "rig-directed",
    evidenceLevel: "semantic",
    cost: "moderate",
    tags: ["arena", "coordinates", "topology", "replica"],
    deterministic: true,
    contexts: [
      "LOCAL_ARTIFACT",
      "LOCAL_MINECRAFT",
      "LIVE_MINECRAFT",
    ],
    producesTraits: ["structural-proof", "semantic-model"],
    prerequisites: ["safe-config-resolution"],
  },
  {
    id: "arena-structure-instance-fidelity",
    executionPhase: "rig-directed",
    evidenceLevel: "semantic",
    cost: "moderate",
    tags: ["arena", "structure", "replica", "placement"],
    deterministic: true,
    contexts: [
      "LOCAL_ARTIFACT",
      "LOCAL_MINECRAFT",
      "LIVE_MINECRAFT",
    ],
    producesTraits: ["structural-proof"],
    prerequisites: ["arena-replica-fidelity"],
  },
  {
    id: "arena-authored-entity-fidelity",
    executionPhase: "rig-directed",
    evidenceLevel: "semantic",
    cost: "moderate",
    tags: ["arena", "entity", "spawn", "replica"],
    deterministic: true,
    contexts: [
      "REMOTE_GITHUB",
      "LOCAL_ARTIFACT",
      "LOCAL_MINECRAFT",
      "LIVE_MINECRAFT",
    ],
    producesTraits: ["structural-proof", "semantic-model"],
    prerequisites: ["safe-config-resolution"],
  },
  {
    id: "pack-identity-continuity",
    executionPhase: "rig-directed",
    evidenceLevel: "semantic",
    cost: "moderate",
    tags: ["manifest", "persistence", "world-db"],
    deterministic: true,
    contexts: [
      "LOCAL_ARTIFACT",
      "LOCAL_MINECRAFT",
      "LIVE_MINECRAFT",
    ],
    producesTraits: ["structural-proof", "semantic-model"],
  },
  {
    id: "arena-spatial-fingerprint",
    executionPhase: "rig-directed",
    evidenceLevel: "semantic",
    cost: "moderate",
    tags: ["arena", "terrain", "world-db", "replica", "chunk"],
    deterministic: true,
    contexts: [
      "LOCAL_ARTIFACT",
      "LOCAL_MINECRAFT",
      "LIVE_MINECRAFT",
    ],
    producesTraits: ["structural-proof"],
    prerequisites: ["arena-replica-fidelity"],
  },
  {
    id: "arena-voxel-proof",
    executionPhase: "rig-directed",
    evidenceLevel: "semantic",
    cost: "expensive",
    tags: ["arena", "terrain", "world-db", "replica", "voxel"],
    deterministic: true,
    contexts: [
      "LOCAL_ARTIFACT",
      "LOCAL_MINECRAFT",
      "LIVE_MINECRAFT",
    ],
    producesTraits: ["structural-proof"],
    prerequisites: ["arena-spatial-fingerprint"],
  },
  {
    id: "arena-block-entity-proof",
    executionPhase: "rig-directed",
    evidenceLevel: "semantic",
    cost: "expensive",
    tags: ["arena", "block-entity", "world-db", "replica"],
    deterministic: true,
    contexts: [
      "LOCAL_ARTIFACT",
      "LOCAL_MINECRAFT",
      "LIVE_MINECRAFT",
    ],
    producesTraits: ["structural-proof"],
    prerequisites: ["arena-replica-fidelity"],
  },
  {
    id: "arena-tick-state-proof",
    executionPhase: "rig-directed",
    evidenceLevel: "semantic",
    cost: "expensive",
    tags: ["arena", "ticks", "world-db", "runtime-state", "replica"],
    deterministic: true,
    contexts: [
      "LOCAL_ARTIFACT",
      "LOCAL_MINECRAFT",
      "LIVE_MINECRAFT",
    ],
    producesTraits: ["structural-proof"],
    prerequisites: ["arena-replica-fidelity"],
  },
  {
    id: "arena-actor-population-proof",
    executionPhase: "rig-directed",
    evidenceLevel: "semantic",
    cost: "very-expensive",
    tags: ["arena", "entity", "actor-db", "world-db", "runtime-state"],
    deterministic: true,
    contexts: [
      "LOCAL_ARTIFACT",
      "LOCAL_MINECRAFT",
      "LIVE_MINECRAFT",
    ],
    producesTraits: ["structural-proof"],
    prerequisites: ["arena-replica-fidelity"],
  },
  {
    id: "arena-runtime-stress",
    executionPhase: "rig-directed",
    evidenceLevel: "runtime",
    cost: "very-expensive",
    tags: ["arena", "multiplayer", "lifecycle", "cleanup", "stress"],
    deterministic: false,
    contexts: [
      "LOCAL_MINECRAFT",
      "LIVE_MINECRAFT",
    ],
    producesTraits: ["runtime-observation"],
    prerequisites: ["arena-concurrency-capacity"],
  },
] as const;
