import type {
  AnalysisCapability,
} from "./types.js";

export const DOMAIN_ANALYSIS_CAPABILITIES:
  readonly AnalysisCapability[] = [
    {
      id: "semantic-ir-state-model",
    executionPhase: "discovery-core",
      knowledgeDomains: ["state-flow"],
      evidenceLevel: "semantic",
      cost: "cheap",
      tags: [
        "state",
        "semantic-ir",
        "flow",
      ],
      deterministic: true,
      contexts: [
        "REMOTE_GITHUB",
        "LOCAL_ARTIFACT",
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "semantic-model",
      ],
    },
    {
      id: "script-spatial-integrity",
    executionPhase: "discovery-core",
      knowledgeDomains: ["spatial-authority"],
      evidenceLevel: "semantic",
      cost: "cheap",
      tags: [
        "spatial",
        "world-mutation",
        "region",
        "script",
      ],
      deterministic: true,
      contexts: [
        "REMOTE_GITHUB",
        "LOCAL_ARTIFACT",
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "semantic-model",
      ],
    },
    {
      id: "script-dataflow-lineage",
    executionPhase: "rig-directed",
      evidenceLevel: "semantic",
      cost: "moderate",
      tags: [
        "script",
        "dataflow",
        "taint",
        "identity",
        "state",
        "lineage",
      ],
      deterministic: true,
      contexts: [
        "REMOTE_GITHUB",
        "LOCAL_ARTIFACT",
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "semantic-model",
      ],
    },
    {
      id: "script-semantic-flow",
    executionPhase: "rig-directed",
      evidenceLevel: "semantic",
      cost: "moderate",
      tags: ["script","dataflow","taint","identity","reward","state","world-mutation"],
      deterministic: true,
      contexts: ["REMOTE_GITHUB","LOCAL_ARTIFACT","LOCAL_MINECRAFT","LIVE_MINECRAFT"],
      producesTraits: ["semantic-model"],
      prerequisites: ["script-dataflow-lineage"],
    },
    {
      id: "script-semantic-flow-witness",
    executionPhase: "rig-directed",
      evidenceLevel: "semantic",
      cost: "moderate",
      tags: ["script","dataflow","taint","witness","identity","state","reward"],
      deterministic: true,
      contexts: ["REMOTE_GITHUB","LOCAL_ARTIFACT","LOCAL_MINECRAFT","LIVE_MINECRAFT"],
      producesTraits: ["semantic-model","structural-proof"],
      prerequisites: ["script-semantic-flow"],
    },
    {
      id: "script-source-recovery",
    executionPhase: "discovery-core",
      evidenceLevel: "static",
      cost: "cheap",
      tags: ["script","bundle","minified","source-map","source-recovery"],
      deterministic: true,
      contexts: ["REMOTE_GITHUB","LOCAL_ARTIFACT","LOCAL_MINECRAFT","LIVE_MINECRAFT"],
      producesTraits: ["structural-proof"],
    },
    {
      id: "script-source-map-binding",
    executionPhase: "discovery-core",
      evidenceLevel: "static",
      cost: "cheap",
      tags: ["script","source-map","bundle","source-recovery"],
      deterministic: true,
      contexts: ["REMOTE_GITHUB","LOCAL_ARTIFACT","LOCAL_MINECRAFT","LIVE_MINECRAFT"],
      producesTraits: ["structural-proof"],
      prerequisites: ["script-source-recovery"],
    },
    {
      id: "arena-lifecycle-integrity",
    executionPhase: "rig-directed",
      knowledgeDomains: ["arena-lifecycle"],
      evidenceLevel: "semantic",
      cost: "cheap",
      tags: [
        "arena",
        "lifecycle",
        "cleanup",
        "generation",
      ],
      deterministic: true,
      contexts: [
        "REMOTE_GITHUB",
        "LOCAL_ARTIFACT",
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "structural-proof",
        "semantic-model",
      ],
    },
    {
      id: "spatial-authority-coverage",
    executionPhase: "rig-directed",
      evidenceLevel: "semantic",
      cost: "cheap",
      tags: [
        "spatial",
        "authority",
        "permission",
        "region",
        "build",
      ],
      deterministic: true,
      contexts: [
        "REMOTE_GITHUB",
        "LOCAL_ARTIFACT",
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "semantic-model",
      ],
    },
    {
      id: "inventory-lifecycle-integrity",
    executionPhase: "rig-directed",
      knowledgeDomains: ["inventory-state"],
      evidenceLevel: "semantic",
      cost: "moderate",
      tags: [
        "inventory",
        "equipment",
        "loadout",
        "respawn",
        "item",
      ],
      deterministic: true,
      contexts: [
        "REMOTE_GITHUB",
        "LOCAL_ARTIFACT",
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "structural-proof",
        "semantic-model",
      ],
    },
    {
      id: "entity-ai-navigation-readiness",
    executionPhase: "rig-directed",
      knowledgeDomains: ["entity-behavior"],
      evidenceLevel: "semantic",
      cost: "moderate",
      tags: [
        "entity",
        "ai",
        "navigation",
        "pathfinding",
        "route",
      ],
      deterministic: true,
      contexts: [
        "REMOTE_GITHUB",
        "LOCAL_ARTIFACT",
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "structural-proof",
        "semantic-model",
      ],
    },
    {
      id: "combat-lifecycle-contract",
    executionPhase: "rig-directed",
      knowledgeDomains: ["combat-lifecycle"],
      evidenceLevel: "semantic",
      cost: "moderate",
      tags: [
        "combat",
        "damage",
        "revive",
        "death",
        "projectile",
      ],
      deterministic: true,
      contexts: [
        "REMOTE_GITHUB",
        "LOCAL_ARTIFACT",
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "semantic-model",
      ],
    },
    {
      id: "chunk-lifecycle-integrity",
    executionPhase: "rig-directed",
      knowledgeDomains: ["chunk-simulation"],
      evidenceLevel: "semantic",
      cost: "moderate",
      tags: [
        "chunk",
        "readiness",
        "ticking-area",
        "residency",
        "lifecycle",
      ],
      deterministic: true,
      contexts: [
        "REMOTE_GITHUB",
        "LOCAL_ARTIFACT",
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "structural-proof",
        "semantic-model",
      ],
    },
    {
      id: "economy-reward-integrity",
    executionPhase: "rig-directed",
      knowledgeDomains: ["economy-reward"],
      evidenceLevel: "semantic",
      cost: "moderate",
      tags: [
        "economy",
        "reward",
        "currency",
        "loot",
        "progression",
      ],
      deterministic: true,
      contexts: [
        "REMOTE_GITHUB",
        "LOCAL_ARTIFACT",
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "semantic-model",
      ],
    },
    {
      id: "persistence-lifecycle-integrity",
    executionPhase: "rig-directed",
      knowledgeDomains: ["persistence-recovery"],
      evidenceLevel: "semantic",
      cost: "moderate",
      tags: [
        "persistence",
        "dynamic-property",
        "recovery",
        "state",
      ],
      deterministic: true,
      contexts: [
        "REMOTE_GITHUB",
        "LOCAL_ARTIFACT",
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "semantic-model",
      ],
    },
    {
      id: "multiplayer-interleaving",
    executionPhase: "rig-directed",
      knowledgeDomains: ["multiplayer-interleaving"],
      evidenceLevel: "semantic",
      cost: "moderate",
      tags: [
        "multiplayer",
        "race",
        "interleaving",
        "generation",
        "arena",
      ],
      deterministic: true,
      contexts: [
        "REMOTE_GITHUB",
        "LOCAL_ARTIFACT",
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "semantic-model",
      ],
    },
    {
      id: "structure-transition-integrity",
    executionPhase: "rig-directed",
      knowledgeDomains: ["world-structure"],
      evidenceLevel: "semantic",
      cost: "moderate",
      tags: [
        "structure",
        "world-mutation",
        "transition",
      ],
      deterministic: true,
      contexts: [
        "REMOTE_GITHUB",
        "LOCAL_ARTIFACT",
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "structural-proof",
        "semantic-model",
      ],
    },
    {
      id: "temporal-ownership-integrity",
    executionPhase: "rig-directed",
      knowledgeDomains: ["temporal-ownership"],
      evidenceLevel: "semantic",
      cost: "moderate",
      tags: [
        "temporal",
        "deferred",
        "ownership",
        "state",
      ],
      deterministic: true,
      contexts: [
        "REMOTE_GITHUB",
        "LOCAL_ARTIFACT",
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "semantic-model",
      ],
    },
    {
      id: "persistence-recovery-runtime",
      executionPhase: "rig-directed",
      evidenceLevel: "runtime",
      cost: "expensive",
      tags: [
        "persistence",
        "recovery",
        "reload",
        "runtime",
      ],
      deterministic: false,
      contexts: [
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "runtime-observation",
      ],
      prerequisites: [
        "persistence-lifecycle-integrity",
      ],
    },
    {
      id: "entity-ai-navigation-runtime",
      executionPhase: "rig-directed",
      evidenceLevel: "runtime",
      cost: "very-expensive",
      tags: [
        "entity",
        "ai",
        "navigation",
        "pathfinding",
        "crowding",
        "recovery",
      ],
      deterministic: false,
      contexts: [
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "runtime-observation",
      ],
      prerequisites: [
        "entity-ai-navigation-readiness",
      ],
    },
    {
      id: "chunk-readiness-runtime",
      executionPhase: "rig-directed",
      evidenceLevel: "runtime",
      cost: "very-expensive",
      tags: [
        "chunk",
        "readiness",
        "loader",
        "ticking-area",
        "runtime",
      ],
      deterministic: false,
      contexts: [
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "runtime-observation",
      ],
      prerequisites: [
        "chunk-lifecycle-integrity",
      ],
    },
    {
      id: "combat-revive-runtime",
      executionPhase: "rig-directed",
      evidenceLevel: "runtime",
      cost: "expensive",
      tags: [
        "combat",
        "revive",
        "death",
        "runtime",
      ],
      deterministic: false,
      contexts: [
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "runtime-observation",
      ],
      prerequisites: [
        "combat-lifecycle-contract",
      ],
    },
    {
      id: "player-capability-authority",
      executionPhase: "rig-directed",
      knowledgeDomains: ["platform-constraints"],
      evidenceLevel: "semantic",
      cost: "cheap",
      tags: [
        "permission",
        "operator",
        "roommaster",
        "gamemode",
        "ability",
        "guard-activation",
      ],
      deterministic: true,
      contexts: [
        "REMOTE_GITHUB",
        "LOCAL_ARTIFACT",
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "contract-evidence",
        "semantic-model",
      ],
    },
    {
      id: "world-rule-authority",
      executionPhase: "rig-directed",
      knowledgeDomains: ["platform-constraints"],
      evidenceLevel: "semantic",
      cost: "cheap",
      tags: [
        "gamerule",
        "world-setting",
        "entity-spawn",
        "authority",
      ],
      deterministic: true,
      contexts: [
        "REMOTE_GITHUB",
        "LOCAL_ARTIFACT",
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "contract-evidence",
        "semantic-model",
      ],
    },
    {
      id: "client-mutation-reconciliation",
      executionPhase: "rig-directed",
      knowledgeDomains: ["platform-constraints"],
      evidenceLevel: "semantic",
      cost: "cheap",
      tags: [
        "client-server",
        "before-event",
        "interaction-cancel",
        "waterlogging",
        "prediction",
      ],
      deterministic: true,
      contexts: [
        "REMOTE_GITHUB",
        "LOCAL_ARTIFACT",
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "semantic-model",
      ],
    },
    {
      id: "physical-containment-proof",
      executionPhase: "rig-directed",
      knowledgeDomains: [
        "spatial-authority",
        "platform-constraints",
      ],
      evidenceLevel: "semantic",
      cost: "moderate",
      tags: [
        "arena",
        "barrier",
        "collision",
        "geometry",
        "containment",
        "flight",
      ],
      deterministic: true,
      contexts: [
        "REMOTE_GITHUB",
        "LOCAL_ARTIFACT",
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "structural-proof",
        "semantic-model",
      ],
    },
    {
      id: "platform-knowledge-applicability",
      executionPhase: "rig-directed",
      knowledgeDomains: ["platform-constraints"],
      evidenceLevel: "semantic",
      cost: "cheap",
      tags: [
        "platform",
        "minecraft",
        "education",
        "compatibility",
        "capability",
        "limits",
      ],
      deterministic: true,
      contexts: [
        "REMOTE_GITHUB",
        "LOCAL_ARTIFACT",
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "contract-evidence",
        "semantic-model",
      ],
    },
  ] as const;
