import type {
  AnalysisCapability,
} from "./types.js";

export const DOMAIN_ANALYSIS_CAPABILITIES:
  readonly AnalysisCapability[] = [
    {
      id: "semantic-ir-state-model",
      evidenceLevel: "semantic",
      cost: "cheap",
      tags: [
        "state",
        "semantic-ir",
        "flow",
      ],
      deterministic: true,
      contexts: [
        "REMOTE_GITHUB",
        "LOCAL_ARTIFACT",
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "semantic-model",
      ],
    },
    {
      id: "script-spatial-integrity",
      evidenceLevel: "semantic",
      cost: "cheap",
      tags: [
        "spatial",
        "world-mutation",
        "region",
        "script",
      ],
      deterministic: true,
      contexts: [
        "REMOTE_GITHUB",
        "LOCAL_ARTIFACT",
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "semantic-model",
      ],
    },
    {
      id: "script-dataflow-lineage",
      evidenceLevel: "semantic",
      cost: "moderate",
      tags: [
        "script",
        "dataflow",
        "taint",
        "identity",
        "state",
        "lineage",
      ],
      deterministic: true,
      contexts: [
        "REMOTE_GITHUB",
        "LOCAL_ARTIFACT",
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "semantic-model",
      ],
    },
    {
      id: "script-semantic-flow",
      evidenceLevel: "semantic",
      cost: "moderate",
      tags: ["script","dataflow","taint","identity","reward","state","world-mutation"],
      deterministic: true,
      contexts: ["REMOTE_GITHUB","LOCAL_ARTIFACT","LOCAL_MINECRAFT","LIVE_MINECRAFT"],
      producesTraits: ["semantic-model"],
      prerequisites: ["script-dataflow-lineage"],
    },
    {
      id: "script-semantic-flow-witness",
      evidenceLevel: "semantic",
      cost: "moderate",
      tags: ["script","dataflow","taint","witness","identity","state","reward"],
      deterministic: true,
      contexts: ["REMOTE_GITHUB","LOCAL_ARTIFACT","LOCAL_MINECRAFT","LIVE_MINECRAFT"],
      producesTraits: ["semantic-model","structural-proof"],
      prerequisites: ["script-semantic-flow"],
    },
    {
      id: "script-source-recovery",
      evidenceLevel: "static",
      cost: "cheap",
      tags: ["script","bundle","minified","source-map","source-recovery"],
      deterministic: true,
      contexts: ["REMOTE_GITHUB","LOCAL_ARTIFACT","LOCAL_MINECRAFT","LIVE_MINECRAFT"],
      producesTraits: ["structural-proof"],
    },
    {
      id: "script-source-map-binding",
      evidenceLevel: "static",
      cost: "cheap",
      tags: ["script","source-map","bundle","source-recovery"],
      deterministic: true,
      contexts: ["REMOTE_GITHUB","LOCAL_ARTIFACT","LOCAL_MINECRAFT","LIVE_MINECRAFT"],
      producesTraits: ["structural-proof"],
      prerequisites: ["script-source-recovery"],
    },
    {
      id: "arena-lifecycle-integrity",
      evidenceLevel: "semantic",
      cost: "cheap",
      tags: [
        "arena",
        "lifecycle",
        "cleanup",
        "generation",
      ],
      deterministic: true,
      contexts: [
        "REMOTE_GITHUB",
        "LOCAL_ARTIFACT",
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "structural-proof",
        "semantic-model",
      ],
    },
    {
      id: "spatial-authority-coverage",
      evidenceLevel: "semantic",
      cost: "cheap",
      tags: [
        "spatial",
        "authority",
        "permission",
        "region",
        "build",
      ],
      deterministic: true,
      contexts: [
        "REMOTE_GITHUB",
        "LOCAL_ARTIFACT",
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "semantic-model",
      ],
    },
    {
      id: "inventory-lifecycle-integrity",
      evidenceLevel: "semantic",
      cost: "moderate",
      tags: [
        "inventory",
        "equipment",
        "loadout",
        "respawn",
        "item",
      ],
      deterministic: true,
      contexts: [
        "REMOTE_GITHUB",
        "LOCAL_ARTIFACT",
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "structural-proof",
        "semantic-model",
      ],
    },
    {
      id: "entity-ai-navigation-readiness",
      evidenceLevel: "semantic",
      cost: "moderate",
      tags: [
        "entity",
        "ai",
        "navigation",
        "pathfinding",
        "route",
      ],
      deterministic: true,
      contexts: [
        "REMOTE_GITHUB",
        "LOCAL_ARTIFACT",
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "structural-proof",
        "semantic-model",
      ],
    },
    {
      id: "combat-lifecycle-contract",
      evidenceLevel: "semantic",
      cost: "moderate",
      tags: [
        "combat",
        "damage",
        "revive",
        "death",
        "projectile",
      ],
      deterministic: true,
      contexts: [
        "REMOTE_GITHUB",
        "LOCAL_ARTIFACT",
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "semantic-model",
      ],
    },
    {
      id: "chunk-lifecycle-integrity",
      evidenceLevel: "semantic",
      cost: "moderate",
      tags: [
        "chunk",
        "readiness",
        "ticking-area",
        "residency",
        "lifecycle",
      ],
      deterministic: true,
      contexts: [
        "REMOTE_GITHUB",
        "LOCAL_ARTIFACT",
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "structural-proof",
        "semantic-model",
      ],
    },
    {
      id: "economy-reward-integrity",
      evidenceLevel: "semantic",
      cost: "moderate",
      tags: [
        "economy",
        "reward",
        "currency",
        "loot",
        "progression",
      ],
      deterministic: true,
      contexts: [
        "REMOTE_GITHUB",
        "LOCAL_ARTIFACT",
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "semantic-model",
      ],
    },
    {
      id: "persistence-lifecycle-integrity",
      evidenceLevel: "semantic",
      cost: "moderate",
      tags: [
        "persistence",
        "dynamic-property",
        "recovery",
        "state",
      ],
      deterministic: true,
      contexts: [
        "REMOTE_GITHUB",
        "LOCAL_ARTIFACT",
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "semantic-model",
      ],
    },
    {
      id: "multiplayer-interleaving",
      evidenceLevel: "semantic",
      cost: "moderate",
      tags: [
        "multiplayer",
        "race",
        "interleaving",
        "generation",
        "arena",
      ],
      deterministic: true,
      contexts: [
        "REMOTE_GITHUB",
        "LOCAL_ARTIFACT",
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "semantic-model",
      ],
    },
    {
      id: "structure-transition-integrity",
      evidenceLevel: "semantic",
      cost: "moderate",
      tags: [
        "structure",
        "world-mutation",
        "transition",
      ],
      deterministic: true,
      contexts: [
        "REMOTE_GITHUB",
        "LOCAL_ARTIFACT",
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "structural-proof",
        "semantic-model",
      ],
    },
    {
      id: "temporal-ownership-integrity",
      evidenceLevel: "semantic",
      cost: "moderate",
      tags: [
        "temporal",
        "deferred",
        "ownership",
        "state",
      ],
      deterministic: true,
      contexts: [
        "REMOTE_GITHUB",
        "LOCAL_ARTIFACT",
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "semantic-model",
      ],
    },
    {
      id: "persistence-recovery-runtime",
      evidenceLevel: "runtime",
      cost: "expensive",
      tags: [
        "persistence",
        "recovery",
        "reload",
        "runtime",
      ],
      deterministic: false,
      contexts: [
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "runtime-observation",
      ],
      prerequisites: [
        "persistence-lifecycle-integrity",
      ],
    },
    {
      id: "entity-ai-navigation-runtime",
      evidenceLevel: "runtime",
      cost: "very-expensive",
      tags: [
        "entity",
        "ai",
        "navigation",
        "pathfinding",
        "crowding",
        "recovery",
      ],
      deterministic: false,
      contexts: [
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "runtime-observation",
      ],
      prerequisites: [
        "entity-ai-navigation-readiness",
      ],
    },
    {
      id: "chunk-readiness-runtime",
      evidenceLevel: "runtime",
      cost: "very-expensive",
      tags: [
        "chunk",
        "readiness",
        "loader",
        "ticking-area",
        "runtime",
      ],
      deterministic: false,
      contexts: [
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "runtime-observation",
      ],
      prerequisites: [
        "chunk-lifecycle-integrity",
      ],
    },
    {
      id: "combat-revive-runtime",
      evidenceLevel: "runtime",
      cost: "expensive",
      tags: [
        "combat",
        "revive",
        "death",
        "runtime",
      ],
      deterministic: false,
      contexts: [
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
      producesTraits: [
        "runtime-observation",
      ],
      prerequisites: [
        "combat-lifecycle-contract",
      ],
    },
  ] as const;
