import type { SourceRef } from "../../project-model/src/source-ref.js";

export type DiagnosticSeverity = "info" | "minor" | "medium" | "critical";

export type DiagnosticCode =
  | "UNRESOLVED_REFERENCE"
  | "AMBIGUOUS_REFERENCE"
  | "DUPLICATE_MANIFEST_UUID"
  | "SUSPICIOUS_REGION_MUTATION"
  | "UNKNOWN_COMMAND_EFFECT"
  | "CROSS_SCOPE_STATE_RISK"
  | "TOPOLOGY_TRANSLATION_OUTLIER"
  | "EDUCATION_FEATURE_STATE_UNKNOWN"
  | "EDUCATION_FEATURE_DISABLED"
  | "SCRIPT_MODULE_UNDECLARED"
  | "STRUCTURE_PARSE_FAILED"
  | "STRUCTURE_LAYER_LENGTH_MISMATCH"
  | "ENTITY_KNOWLEDGE_PREREQUISITE_GAP"
  | "ENTITY_RUNTIME_BEHAVIOR_LIMIT"
  | "ENTITY_SENSOR_EVENT_UNDEFINED"
  | "ENTITY_TRIGGER_EVENT_UNDEFINED"
  | "ENTITY_EVENT_COMPONENT_GROUP_UNDEFINED"
  | "ENTITY_EVENT_INTERNAL_REACHABILITY_UNKNOWN"
  | "STRUCTURE_LOAD_TARGET_MISSING"
  | "STRUCTURE_LOAD_TARGET_AMBIGUOUS"
  | "STRUCTURE_LOAD_CONTENT_EXCLUDED"
  | "STRUCTURE_LOAD_PROBABILISTIC_RUNTIME_CONTENT"
  | "CHUNK_LIFECYCLE_RUNTIME_RISK"
  | "STRUCTURE_EMBEDDED_COMMAND_EFFECT_UNKNOWN"
  | "STRUCTURE_COMMAND_CHAIN_TOPOLOGY_RISK"
  | "DIALOGUE_SCENE_DUPLICATE"
  | "SCRIPT_RESTRICTED_EXECUTION_MUTATION"
  | "SCRIPT_API_VERSION_INCOMPATIBLE"
  | "SCRIPT_API_PRERELEASE_SYMBOL"
  | "SCRIPT_API_DEPRECATED_SYMBOL"
  | "SCRIPT_API_REMOVED_SYMBOL"
  | "SCRIPT_API_SIGNATURE_INCOMPATIBLE"
  | "SCRIPT_API_RETURN_CONTRACT_RISK"
  | "SCRIPT_API_PROPERTY_WRITE_INCOMPATIBLE"
  | "SCRIPT_API_ENUM_VALUE_INCOMPATIBLE"
  | "KNOWLEDGE_RELATION_VIOLATION"
  | "KNOWLEDGE_EVIDENCE_GAP"
  | "TELEMETRY_EVENTS_DROPPED";

export interface DiagnosticFinding {
  id: string;
  code: DiagnosticCode;
  severity: DiagnosticSeverity;
  message: string;
  source?: SourceRef;
  relatedNodeIds?: readonly string[];
  data?: Readonly<Record<string, unknown>>;
}
