import type {
  TaskCapability,
} from "./types.js";

const ALL_STATIC_CONTEXTS = [
  "REMOTE_GITHUB",
  "LOCAL_ARTIFACT",
  "LOCAL_MINECRAFT",
  "LIVE_MINECRAFT",
] as const;

export const BUILTIN_TASK_CAPABILITIES:
  readonly TaskCapability[] = [
    {
      id: "source.scripts.core",
      owner: "analyzers/scripts",
      pathPrefixes: [
        "analyzers/scripts/src/parse.ts",
        "analyzers/scripts/src/types.ts",
        "analyzers/scripts/src/index.ts",
        "analyzers/scripts/src/receiver-inference.ts",
      ],
      deterministic: true,
      cacheable: true,
      cost: "moderate",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "foundation.dataflow",
      owner: "packages/dataflow",
      pathPrefixes: [
        "packages/dataflow/src/*",
      ],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "source.scripts.dataflow",
      owner: "analyzers/scripts",
      pathPrefixes: [
        "analyzers/scripts/src/dataflow.ts",
      ],
      dependsOn: [
        "source.scripts.core",
        "foundation.dataflow",
      ],
      deterministic: true,
      cacheable: true,
      cost: "moderate",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "source.scripts.semantic-flow",
      owner: "analyzers/scripts",
      pathPrefixes: [
        "analyzers/scripts/src/semantic-flow-bindings.ts",
      ],
      dependsOn: ["source.scripts.dataflow"],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "source.scripts.semantic-flow-witness",
      owner: "analyzers/scripts",
      pathPrefixes: [
        "analyzers/scripts/src/semantic-flow-witness.ts",
      ],
      dependsOn: [
        "source.scripts.semantic-flow",
        "foundation.dataflow",
      ],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "source.scripts.recovery",
      owner: "analyzers/scripts",
      pathPrefixes: [
        "analyzers/scripts/src/source-recovery.ts",
      ],
      dependsOn: ["source.scripts.core"],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "source.scripts.source-map",
      owner: "analyzers/scripts",
      pathPrefixes: [
        "analyzers/scripts/src/source-map-binding.ts",
      ],
      dependsOn: ["source.scripts.recovery"],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "source.scripts.arena",
      owner: "analyzers/scripts",
      pathPrefixes: [
        "analyzers/scripts/src/arena-*",
        "analyzers/scripts/src/cleanup-resource-*",
        "analyzers/scripts/src/global-lease-*",
      ],
      dependsOn: ["source.scripts.core"],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "source.scripts.inventory",
      owner: "analyzers/scripts",
      pathPrefixes: [
        "analyzers/scripts/src/inventory-*",
      ],
      dependsOn: ["source.scripts.core"],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "source.scripts.combat",
      owner: "analyzers/scripts",
      pathPrefixes: [
        "analyzers/scripts/src/combat-*",
      ],
      dependsOn: ["source.scripts.core"],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "source.scripts.chunks",
      owner: "analyzers/scripts",
      pathPrefixes: [
        "analyzers/scripts/src/chunk-*",
      ],
      dependsOn: ["source.scripts.core"],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "source.scripts.economy",
      owner: "analyzers/scripts",
      pathPrefixes: [
        "analyzers/scripts/src/economy-*",
      ],
      dependsOn: ["source.scripts.core"],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "source.scripts.persistence",
      owner: "analyzers/scripts",
      pathPrefixes: [
        "analyzers/scripts/src/persistent-*",
        "analyzers/scripts/src/persistence-*",
      ],
      dependsOn: ["source.scripts.core"],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "source.entities.core",
      owner: "analyzers/entities",
      pathPrefixes: [
        "analyzers/entities/src/parse.ts",
        "analyzers/entities/src/types.ts",
        "analyzers/entities/src/state-graph.ts",
        "analyzers/entities/src/runtime-evidence.ts",
      ],
      deterministic: true,
      cacheable: true,
      cost: "moderate",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "source.entities.ai",
      owner: "analyzers/entities",
      pathPrefixes: [
        "analyzers/entities/src/ai-stack.ts",
        "analyzers/entities/src/navigation.ts",
        "analyzers/entities/src/targeting.ts",
        "analyzers/entities/src/attack.ts",
        "analyzers/entities/src/reachability.ts",
        "analyzers/entities/src/sensors.ts",
      ],
      dependsOn: ["source.entities.core"],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "source.entities.economy",
      owner: "analyzers/entities",
      pathPrefixes: [
        "analyzers/entities/src/loot.ts",
      ],
      dependsOn: ["source.entities.core"],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "behavior.core",
      owner: "packages/behavior-model",
      pathPrefixes: [
        "packages/behavior-model/src/types.ts",
        "packages/behavior-model/src/provenance.ts",
        "packages/behavior-model/src/transition.ts",
        "packages/behavior-model/src/compose.ts",
        "packages/behavior-model/src/minecraft/index.ts",
      ],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "behavior.arena",
      owner: "packages/behavior-model",
      pathPrefixes: [
        "packages/behavior-model/src/minecraft/arena-lifecycle.ts",
      ],
      dependsOn: ["behavior.core"],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "behavior.spatial",
      owner: "packages/behavior-model",
      pathPrefixes: [
        "packages/behavior-model/src/minecraft/spatial-authority.ts",
      ],
      dependsOn: ["behavior.core"],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "behavior.inventory",
      owner: "packages/behavior-model",
      pathPrefixes: [
        "packages/behavior-model/src/minecraft/inventory-*",
      ],
      dependsOn: ["behavior.core"],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "behavior.entity-ai",
      owner: "packages/behavior-model",
      pathPrefixes: [
        "packages/behavior-model/src/minecraft/navigation-*",
      ],
      dependsOn: ["behavior.core"],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "behavior.combat",
      owner: "packages/behavior-model",
      pathPrefixes: [
        "packages/behavior-model/src/minecraft/combat-*",
      ],
      dependsOn: ["behavior.core"],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "behavior.chunks",
      owner: "packages/behavior-model",
      pathPrefixes: [
        "packages/behavior-model/src/minecraft/chunk.ts",
      ],
      dependsOn: ["behavior.core"],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "behavior.economy",
      owner: "packages/behavior-model",
      pathPrefixes: [
        "packages/behavior-model/src/minecraft/economy-*",
      ],
      dependsOn: ["behavior.core"],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "domain.persistence",
      owner: "packages/orchestrator",
      pathPrefixes: [
        "packages/orchestrator/src/persistence-*",
      ],
      dependsOn: [
        "source.scripts.persistence",
      ],
      deterministic: true,
      cacheable: true,
      cost: "moderate",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "domain.arena-lifecycle",
      owner: "packages/orchestrator",
      pathPrefixes: [
        "packages/orchestrator/src/arena-lifecycle-*",
        "packages/orchestrator/src/arena-cleanup-*",
      ],
      dependsOn: [
        "source.scripts.arena",
        "behavior.arena",
      ],
      deterministic: true,
      cacheable: true,
      cost: "moderate",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "domain.spatial-authority",
      owner: "packages/orchestrator",
      pathPrefixes: [
        "packages/orchestrator/src/spatial-authority-*",
      ],
      dependsOn: ["behavior.spatial"],
      deterministic: true,
      cacheable: true,
      cost: "moderate",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "domain.inventory",
      owner: "packages/orchestrator",
      pathPrefixes: [
        "packages/orchestrator/src/inventory-*",
      ],
      dependsOn: [
        "source.scripts.inventory",
        "behavior.inventory",
      ],
      deterministic: true,
      cacheable: true,
      cost: "moderate",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "domain.entity-ai",
      owner: "packages/orchestrator",
      pathPrefixes: [
        "packages/orchestrator/src/entity-ai-*",
        "packages/orchestrator/src/entity-navigation-*",
        "packages/orchestrator/src/route-navigation-*",
      ],
      dependsOn: [
        "source.entities.ai",
        "behavior.entity-ai",
      ],
      deterministic: true,
      cacheable: true,
      cost: "moderate",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "domain.combat",
      owner: "packages/orchestrator",
      pathPrefixes: [
        "packages/orchestrator/src/combat-*",
      ],
      dependsOn: [
        "source.scripts.combat",
        "behavior.combat",
      ],
      deterministic: true,
      cacheable: true,
      cost: "moderate",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "domain.chunks",
      owner: "packages/orchestrator",
      pathPrefixes: [
        "packages/orchestrator/src/chunk-*",
      ],
      dependsOn: [
        "source.scripts.chunks",
        "behavior.chunks",
      ],
      deterministic: true,
      cacheable: true,
      cost: "moderate",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "domain.economy",
      owner: "packages/orchestrator",
      pathPrefixes: [
        "packages/orchestrator/src/economy-*",
        "packages/orchestrator/src/reward-source-*",
      ],
      dependsOn: [
        "source.scripts.economy",
        "source.scripts.inventory",
        "source.entities.economy",
        "behavior.economy",
      ],
      deterministic: true,
      cacheable: true,
      cost: "moderate",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "domain.player-capability",
      owner: "packages/orchestrator",
      pathPrefixes: [
        "packages/orchestrator/src/inspection/player-capability-surface-analysis.ts",
        "packages/orchestrator/src/inspection/capability-mutation-footprint-analysis.ts",
        "packages/orchestrator/src/inspection/capability-exposure-stage.ts",
      ],
      dependsOn: [
        "source.scripts.core",
        "behavior.arena",
      ],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "domain.world-rule-authority",
      owner: "packages/orchestrator",
      pathPrefixes: [
        "packages/orchestrator/src/inspection/world-rule-authority-analysis.ts",
      ],
      dependsOn: [
        "source.scripts.core",
      ],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "domain.client-reconciliation",
      owner: "packages/orchestrator",
      pathPrefixes: [
        "packages/orchestrator/src/inspection/client-mutation-reconciliation-analysis.ts",
      ],
      dependsOn: [
        "source.scripts.core",
      ],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "domain.physical-containment",
      owner: "packages/orchestrator",
      pathPrefixes: [
        "packages/orchestrator/src/arena/arena-voxel-proof.ts",
      ],
      dependsOn: [
        "domain.spatial-authority",
      ],
      deterministic: true,
      cacheable: true,
      cost: "moderate",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "runtime.cross-version-differential-plan",
      owner: "packages/runtime-lab",
      pathPrefixes: [
        "packages/runtime-lab/src/cross-version-differential-plan.ts",
      ],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "runtime.cross-version-differential-executor",
      owner: "packages/runtime-lab",
      pathPrefixes: [
        "packages/runtime-lab/src/cross-version-differential-executor.ts",
      ],
      dependsOn: [
        "runtime.cross-version-differential-plan",
      ],
      deterministic: false,
      cacheable: false,
      cost: "very-expensive",
      contexts: [
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
    },
    {
      id: "runtime.record-replay-contract",
      owner: "packages/reliability",
      pathPrefixes: [
        "packages/reliability/src/runtime-session-replay.ts",
      ],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "runtime.semantic-convention",
      owner: "packages/project-model",
      pathPrefixes: [
        "packages/project-model/src/runtime-semantic-convention.ts",
      ],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "runtime.persistence",
      owner: "packages/runtime-lab",
      pathPrefixes: [
        "packages/runtime-lab/src/persistence-*",
      ],
      dependsOn: ["domain.persistence"],
      deterministic: false,
      cacheable: false,
      cost: "expensive",
      contexts: [
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
    },
    {
      id: "runtime.entity-ai",
      owner: "packages/runtime-lab",
      pathPrefixes: [
        "packages/runtime-lab/src/entity-navigation-*",
      ],
      dependsOn: ["domain.entity-ai"],
      deterministic: false,
      cacheable: false,
      cost: "very-expensive",
      contexts: [
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
    },
    {
      id: "runtime.chunks",
      owner: "packages/runtime-lab",
      pathPrefixes: [
        "packages/runtime-lab/src/chunk-*",
      ],
      dependsOn: ["domain.chunks"],
      deterministic: false,
      cacheable: false,
      cost: "very-expensive",
      contexts: [
        "LOCAL_MINECRAFT",
        "LIVE_MINECRAFT",
      ],
    },
    {
      id: "reliability.behavior-patterns",
      owner: "packages/reliability-search",
      pathPrefixes: [
        "packages/reliability-search/src/behavioral-pattern-library.ts",
      ],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "reliability.metamorphic",
      owner: "packages/reliability-search",
      pathPrefixes: [
        "packages/reliability-search/src/metamorphic.ts",
      ],
      deterministic: true,
      cacheable: false,
      cost: "moderate",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "reliability.parser-robustness",
      owner: "packages/reliability-search",
      pathPrefixes: [
        "packages/reliability-search/src/parser-robustness.ts",
      ],
      deterministic: true,
      cacheable: false,
      cost: "moderate",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "reliability.coverage-quality",
      owner: "packages/reliability-search",
      pathPrefixes: [
        "packages/reliability-search/src/coverage-quality-dashboard.ts",
        "packages/reliability-search/src/generated-known-limits.ts",
      ],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "projection.world-model",
      owner: "packages/orchestrator",
      pathPrefixes: [
        "packages/orchestrator/src/gameplay-world-model.ts",
      ],
      dependsOn: [
        "domain.arena-lifecycle",
        "domain.persistence",
        "domain.spatial-authority",
        "domain.inventory",
        "domain.entity-ai",
        "domain.combat",
        "domain.chunks",
        "domain.economy",
        "domain.player-capability",
        "domain.world-rule-authority",
        "domain.client-reconciliation",
        "domain.physical-containment",
      ],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "projection.workflow",
      owner: "packages/orchestrator",
      pathPrefixes: [
        "packages/orchestrator/src/map-engineering-workflow.ts",
      ],
      dependsOn: ["projection.world-model"],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "knowledge.freshness",
      owner: "packages/knowledge",
      pathPrefixes: [
        "packages/knowledge/src/freshness.ts",
      ],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "diagnosis.declarative-rules",
      owner: "packages/diagnostic-reasoning",
      pathPrefixes: [
        "packages/diagnostic-reasoning/src/declarative-rules.ts",
      ],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "diagnosis.calibration",
      owner: "packages/diagnostic-reasoning",
      pathPrefixes: [
        "packages/diagnostic-reasoning/src/calibration.ts",
      ],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "repair.routing",
      owner: "packages/orchestrator",
      pathPrefixes: [
        "packages/orchestrator/src/repair-strategy-*",
        "packages/orchestrator/src/repair-realiz*",
      ],
      dependsOn: ["projection.world-model"],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "context.dataflow-slice",
      owner: "packages/orchestrator",
      pathPrefixes: [
        "packages/orchestrator/src/script-dataflow-context.ts",
      ],
      dependsOn: ["source.scripts.dataflow"],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
    {
      id: "context.compile",
      owner: "packages/orchestrator",
      pathPrefixes: [
        "packages/orchestrator/src/context-compiler.ts",
      ],
      dependsOn: ["projection.world-model"],
      deterministic: true,
      cacheable: true,
      cost: "cheap",
      contexts: ALL_STATIC_CONTEXTS,
    },
  ] as const;
